### ISSUE TITLE
随机定时bug

### ISSUE THREAD

**Issue by Air433up** [Oreomeow/checkinpanel#100]
青龙面板2.10.10下，一运行随机定时便会提示“服务异常，请手动执行ql check检查服务状态”，然后就必须重启面板才能恢复正常

**Comment by night-raise** [comment]
@Air433up 等我过两天看看

**Comment by Air433up** [comment]
好的，辛苦啦

**Comment by night-raise** [comment]
我这边测试结果是由于容器重启导致的服务异常。你那边有啥日志吗？

**Comment by Oreomeow** [comment]
@night-raise 青龙已经不用 db 文件了，你去写 api 操作的

**Comment by night-raise** [comment]
@Oreomeow 你没看见最后一个issue一直挂着？
还没来得及有空

**Comment by night-raise** [comment]
找到问题了。后续修一下
