### ISSUE TITLE
依赖无法安装，求大佬解决一下

### ISSUE THREAD

**Issue by avinrock** [Oreomeow/checkinpanel#103]
## 开始执行... 2022-02-16 21:54:27

fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.9-62-g8596bdad23 [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main]
v3.12.9-58-g838b7dc4f5 [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community]
OK: 12765 distinct packages available
bash 已安装
curl 已安装
ERROR: unable to select packages:
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add gcc !!
git 已安装
jq 已安装
ERROR: unable to select packages:
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add libffi-dev !!
ERROR: unable to select packages:
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........

**Comment by Oreomeow** [comment]
要么运行国内加速任务，要么更新青龙

https://github.com/whyour/qinglong/commit/fc4562eca23ea47750c1cca329bcdc442e8da55e#diff-a7a92e793e13161b58a26c6c1c0445fef52d1b6fd0cc081d71701d0a1ad5c089R13

**Comment by avinrock** [comment]
> 要么运行国内加速任务，要么更新青龙
> 
> [whyour/qinglong@fc4562e#diff-a7a92e793e13161b58a26c6c1c0445fef52d1b6fd0cc081d71701d0a1ad5c089R13](https://github.com/whyour/qinglong/commit/fc4562eca23ea47750c1cca329bcdc442e8da55e#diff-a7a92e793e13161b58a26c6c1c0445fef52d1b6fd0cc081d71701d0a1ad5c089R13)

我从2.10.13刷回了2.10.7版本，可以正常装依赖了。谢谢

**Comment by avinrock** [comment]
修改apk软件源的文件

vi /etc/apk/repositories
就会显示如下

root@ql:/ql $ vi /etc/apk/repositories
https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main
https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community
~
~
~
~
- /etc/apk/repositories 1/2 50%
这里可看到 v3.14 ，也有人可能会用的是 latest-stable （稳定版本）。

退出vi，先按Esc键，然后输入 :q  ，然后回车即可退出

这些版本的源没有python以及python-dev，它们在v3.4老版本才有，但是我对比了下版本，

从v3.4版本后，python改名成python2了，所以其实并不用改源，直接改用python2即可。

如果还是想改源的话，改源版本如下：

改版本，v3.14替换成你自己通过vi查询到的apk源版本

sed -i 's/v3.14/v3.4/g' /etc/apk/repositories
更新apk索引以生效

apk update
