### ISSUE TITLE
请问utils.py可以添加前缀吗？

### ISSUE THREAD

**Issue by fidcz** [Oreomeow/checkinpanel#109]
在青龙老版本和其他库，会替换其他库的utils.py文件或者被其他库的替换。我还拉了其他的网易云音乐人签到，两个utils.py就一直在互相替换，导致会有一边的任务跑不起来....
[https://github.com/chen310/NeteaseCloudMusicTasks](url) 现在拉的是这个，也在他们那提issues了

**Comment by Oreomeow** [comment]
升级青龙版本

**Comment by FlechazoPh** [comment]
同样的问题，青龙新版本有时候会有BUG，所以一直用老版本比较稳定，希望能加个类似 oreomeow_ 的前缀
