### ISSUE TITLE
SMZDM报错，第一天填写ck正常运行，第二天开始就报错了

### ISSUE THREAD

**Issue by GTXGOGOGO** [Oreomeow/checkinpanel#110]
已经尝试重新登陆获取ck，仍然报错
![IMG_2964](https://user-images.githubusercontent.com/61621084/158094262-dc2f83ce-b772-41d2-a576-b22ecbd5c4c2.PNG)
![Uploading IMG_2965.PNG…]()

**Comment by GTXGOGOGO** [comment]
找到原因了，不知道为什么去读了iqiyi的ck，我把aqiyi的ck删除了就正常了

**Comment by Amongsterdevil** [comment]
完全没明白
