### ISSUE TITLE
青龙新版本修改了数据路径如何修改？

### ISSUE THREAD

**Issue by Cyiming** [Oreomeow/checkinpanel#112]
新版本青龙数据目录为 /ql/data/config/  

造成脚本找不到check.toml文件

我应该如何修改脚本查找路径

**Comment by Oreomeow** [comment]
已初步适配，可以进行测试

**Comment by changyizhen** [comment]
> 已初步适配，可以进行测试

如何测试 重新拉库还是？

**Comment by Oreomeow** [comment]
@changyizhen 重新拉库更新即可

**Comment by night-raise** [comment]
@changyizhen 等我看看

**Comment by night-raise** [comment]
@changyizhen 没有复现？你看看你配置文件有没有问题？

**Comment by changyizhen** [comment]
> @changyizhen 没有复现？你看看你配置文件有没有问题？

没有啊 脚本和配置文件都搜了 没有上海  那块的配置只有一个城市 好奇怪 

你改成别的城市 就推送一个么

**Comment by Oreomeow** [comment]
@changyizhen 把配置文件这一块末尾的逗号删掉

**Comment by Cyiming** [comment]
> @changyizhen 把配置文件这一块末尾的逗号删掉

我原来是省份，城市 格式  只改成城市好了
