### ISSUE TITLE
猫大，我能问一个签到涉及的知识么。

### ISSUE THREAD

**Issue by Cyiming** [Oreomeow/checkinpanel#116]
我是搜索代码来这里的 我注意到您ck_bak//ss_kjwj.py签到 用的方法是先登录 然后再签到 

这样ck不会失效 但是会让自己浏览器的登录失效很不便  我之前是尝试直接请求签到接口wp-json/b2/v1/userMission 但是奇怪的是返回的是前一天签到的结果 我也尝试换请求头、换ip、用session、换时间都不行

最后我发现 只要我在浏览器中刷新下 再用代码请求接口就能签到了 甚至我反复重新登录Authorization变化了无数遍 但是只要当天我刷新了浏览器 用最开始旧的Authorization还是可以签到成功 我不知道怎么代码模拟浏览器刷新的那一下

同时我注意到那段代码放在了备份里 而不是这个库中 是失效了吗

这个问题我想了好几天了 得不到答案 如果能得到指点一二 不胜感激

**Comment by Oreomeow** [comment]
@Cyiming 加入 tg 群有收获

**Comment by Cyiming** [comment]
> @Cyiming 加入 tg 群有收获

我好像找到了猫粮投喂频道 不能发言 看了所有消息 没有涉及该部分的啊

我又想了下 可能是在刷新页面时网页请求了其他地址刷新了用户在服务器的信息 或者不是请求而是js执行的

就得明天试验了 想的头大

**Comment by Oreomeow** [comment]
> > @Cyiming 加入 tg 群有收获
> 
> 我好像找到了猫粮投喂频道 不能发言 看了所有消息 没有涉及该部分的啊
> 
> 我又想了下 可能是在刷新页面时网页请求了其他地址刷新了用户在服务器的信息 或者不是请求而是js执行的
> 
> 就得明天试验了 想的头大

点一下标题下面的标签
