### ISSUE TITLE
[BUG] Glados 签到的返回值变了，更新如下：

### ISSUE THREAD

**Issue by FlechazoPh** [Oreomeow/checkinpanel#118]
[BUG] Glados 签到的返回报错 ，日志如下：

<img width="497" alt="image" src="https://user-images.githubusercontent.com/94276146/161376250-04d9eef5-f5f2-4311-b00c-cc038d32b87e.png">

希望能更新一下，每次签到一天可以无限续期

**Comment by Oreomeow** [comment]
4f754e0f4ee61e794b082f311d90a62b4dd02f9d

**Comment by Amongsterdevil** [comment]
Id 87652435 密碼 abhijeet 909090 檢查這個文件
