### ISSUE TITLE
GLaDOS运行问题

### ISSUE THREAD

**Issue by EchoChan314** [Oreomeow/checkinpanel#120]
GLaDOS

--------------------
Msg: Check in error!
Error:
Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_glados.py", line 105, in main
    left_days = int(status_response["data"]["leftDays"])
ValueError: invalid literal for int() with base 10: '709.0000000000000000'

**Comment by FlechazoPh** [comment]
同报错
报错日志：
<img width="527" alt="image" src="https://user-images.githubusercontent.com/94276146/161925660-8383fc67-70bd-4ba1-854a-8d5751e66d39.png">
