### ISSUE TITLE
啊啊啊！

### ISSUE THREAD

**Issue by night-raise** [Oreomeow/checkinpanel#121]
我tg号被封了，裂开。

**Comment by night-raise** [comment]
你没发现我 tg 号没了？

**Comment by night-raise** [comment]
https://t.me/xhqcankao/2838
这个吧，只感觉是我运气不好被干掉了...tg 太坏了，居然封人形

**Comment by Oreomeow** [comment]
@night-raise 你回不来了？

**Comment by night-raise** [comment]
我一直申请不了；等我过两天重新买个gv注册个新号。

**Comment by Oreomeow** [comment]
一言那个地方没开启的话会多出两个空行和 `>`，你再想想

**Comment by fscarmen** [comment]
> 我一直申请不了；等我过两天重新买个gv注册个新号。

冬少，他们都说你15天

**Comment by night-raise** [comment]
怎么样，新的推送还行吧？

**Comment by Oreomeow** [comment]
@night-raise 你怎么还回不来

**Comment by Oreomeow** [comment]
@night-raise 要不给你一个号？

**Comment by night-raise** [comment]
要要要，非常要。

邮箱： summerdown@yandex.com
