### ISSUE TITLE
青龙签到依赖

### ISSUE THREAD

**Issue by GD2021** [Oreomeow/checkinpanel#133]
![image](https://user-images.githubusercontent.com/81171294/177047187-57a37000-69ab-4acd-b76b-49a6700d5af6.png)

大佬，执行签到依赖的时候显示这个安装失败，怎么办呢

**Comment by GD2021** [comment]
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
v3.12.12-40-gdc5d0f0e3f [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main]
v3.12.12-28-gaf427ae836 [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community]
OK: 12649 distinct packages available
bash 已安装
curl 已安装
gcc 已安装
git 已安装
jq 已安装
ERROR: unable to select packages:
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add libffi-dev !!
ERROR: unable to select packages:
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add make !!
musl-dev 已安装
ERROR: unable to select packages:
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add openssl-dev !!
perl 已安装
ERROR: unable to select packages:
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add perl-app-cpanminus !!
ERROR: unable to select packages:
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add perl-dev !!
py3-pip 已安装
python3 已安装
python3-dev 已安装
wget 已安装
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (22.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
bs4 已安装
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.8
      creating build/lib.linux-aarch64-3.8/cffi
      copying cffi/error.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/recompiler.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/lock.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/__init__.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/commontypes.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/api.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/model.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/cparser.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/verifier.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/_embedding.h -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.8/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-aarch64-3.8
      creating build/temp.linux-aarch64-3.8/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.8/c/_cffi_backend.o
      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
         15 | #include <ffi.h>
            |          ^~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cffi
  error: subprocess-exited-with-error
  
  × Running setup.py install for cffi did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.8
      creating build/lib.linux-aarch64-3.8/cffi
      copying cffi/error.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/recompiler.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/lock.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/__init__.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/commontypes.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/api.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/model.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/cparser.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/verifier.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/_embedding.h -> build/lib.linux-aarch64-3.8/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.8/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-aarch64-3.8
      creating build/temp.linux-aarch64-3.8/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.8/c/_cffi_backend.o
      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
         15 | #include <ffi.h>
            |          ^~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cffi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
!! 自动安装失败，请尝试进入容器后执行 pip3 install cryptography !!
dateparser 已安装
feedparser 已安装
peewee 已安装
pyaes 已安装
pyppeteer 已安装
requests 已安装
rsa 已安装
schedule 已安装
tomli 已安装

up to date in 1s
@iarna/toml 已正确安装
axios 已正确安装
crypto-js 已正确安装
got 已正确安装
checkinpanel@4.0.0 /ql/scripts/Oreomeow_checkinpanel_master
├── @iarna/toml@2.2.5
├── axios@0.23.0
├── cron-parser@4.5.0
├── crypto-js@4.1.1
└── got@11.8.5

ins_pkg.sh: line 123: cpanm: command not found
.......... cpanm -fn App::cpm begin ..........
---------- cpanm -fn App::cpm succeed ----------
cpm 0.997009 (./cpm)
This is a self-contained version, 0.997009 (https://github.com/skaji/cpm/tree/0.997009)
perl version v5.30.3 (perl)

  %Config:
    archname=aarch64-linux-thread-multi
    installsitelib=/usr/local/share/perl5/site_perl
    installsitebin=/usr/local/bin
    installman1dir=/usr/share/man/man1
    installman3dir=/usr/share/man/man3
    sitearchexp=/usr/local/lib/perl5/site_perl
    sitelibexp=/usr/local/share/perl5/site_perl
    vendorarch=/usr/lib/perl5/vendor_perl
    vendorlibexp=/usr/share/perl5/vendor_perl
    archlibexp=/usr/lib/perl5/core_perl
    privlibexp=/usr/share/perl5/core_perl
  %ENV:
  @INC:
    FatPacked::367711743632=HASH(0x559d53ee90)
    /usr/local/lib/perl5/site_perl
    /usr/local/share/perl5/site_perl
    /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/core_perl
    /usr/share/perl5/core_perl
No documentation found for "File::Slurp".
ins_pkg.sh: line 139: cpm: command not found
.......... cpm install -g File::Slurp begin ..........
---------- cpm install -g File::Slurp succeed ----------
No documentation found for "JSON5".
ins_pkg.sh: line 139: cpm: command not found
.......... cpm install -g JSON5 begin ..........
---------- cpm install -g JSON5 succeed ----------
No documentation found for "TOML::Dumper".
ins_pkg.sh: line 139: cpm: command not found
.......... cpm install -g TOML::Dumper begin ..........
---------- cpm install -g TOML::Dumper succeed ----------

## 执行结束... 2022-07-05 22:58:52 耗时 200 秒

**Comment by GD2021** [comment]
大佬能帮我看看吗？

**Comment by Oreomeow** [comment]
> ## 开始执行... 2022-07-05 23:48:36
> 
> 尝试检查运行环境...
> 成功，当前环境为: 青龙面板。
> 环境检查结束。
> 
> 配置文件 (notify.toml) 检查开始...
> 未找到配置文件（不一定是错误），路径为: /ql/config/notify.toml。
> 配置文件检查结束。
> 
> checkinpanel 当前版本：20211219-4-020，不在 8-12 点内，跳过版本检查。
> 
> 配置文件 (check.toml) 检查开始...
> 在 /ql/config/check.toml 发现配置文件。
> 配置文件检查结束。
> 
> 错误：配置文件 /ql/config/check.toml 格式不对，请学习 https://toml.io/cn/v1.0.0
> 错误信息：
> Traceback (most recent call last):
>   File "/ql/scripts/yxnwh_checkin_main/utils.py", line 37, in get_data
>     DATA = tomli.load(open(check_config, "rb"))
>   File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 66, in load
>     return loads(s, parse_float=parse_float)
>   File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 127, in loads
>     raise suffixed_err(
> tomli.TOMLDecodeError: Expected newline or end of document after a statement (at line 89, column 390)
> 
> 
> ## 执行结束... 2022-07-05 23:48:37 耗时 1 秒

出错位置在 89 行 390 列
