### ISSUE TITLE
SMZDM PY 签到报错

### ISSUE THREAD

**Issue by smallfount** [Oreomeow/checkinpanel#137]
Hello,
checkinpanel的 SMZDM PY版本签到报错，提示获取新的cookie
重新获取cookie以后问题依旧。
同时，js版本可以正常完成任务，无论是新的还是旧的cookie.
toml文件里我就找到一个什么值得买的选项。。。应该不会是配置错了吧？
麻烦大佬看一眼？

**Comment by Oreomeow** [comment]
完整 cookie 格式

```
__xkguid=xxxxxxxxxxxxxxxxxxxxxxx; r_sort_type=xxxxx; __jsluid_s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; smzdm_user_source=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; device_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; homepage_sug=c; _zdmA.uid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; _zdmA.vid=x; footer_floating_layer=x; ad_date=xx; bannerCounter=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ad_json_feed=xxxxxx; _zdmA.time=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sess=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; user=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; smzdm_id=xxxxxxxxxx;
```

**Comment by smallfount** [comment]
> 完整 cookie 格式
> 
> ```
> cookie = "__xkguid=xxxxxxxxxxxxxxxxxxxxxxx; r_sort_type=xxxxx; __jsluid_s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; smzdm_user_source=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; device_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; homepage_sug=c; _zdmA.uid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; _zdmA.vid=x; footer_floating_layer=x; ad_date=xx; bannerCounter=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ad_json_feed=xxxxxx; _zdmA.time=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sess=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; user=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; smzdm_id=xxxxxxxxxx;"
> ```

哦哦，要用完整格式的啊。。确认没问题了，多谢

**Comment by smallfount** [comment]
cookie补完就行了
