### ISSUE TITLE
张大妈签到失败

### ISSUE THREAD

**Issue by LGinC** [Oreomeow/checkinpanel#14]
'latin-1' codec can't encode characters in position 567-570: ordinal not in range(256)
![image](https://user-images.githubusercontent.com/15363011/133293298-6aeb58d4-488d-415e-a74f-cc50da6747f9.png)

**Comment by night-raise** [comment]
看起来是编码错误，请在猫猫回复前不要重置你的环境，方便问题复现。

这个问题是编码问题引起的，需要进一步调试。

**Comment by Oreomeow** [comment]
检查配置文件里面中文是否有 // 注释，请不要删除中文行前的 //

**Comment by night-raise** [comment]
@Oreomeow 如果有必要的话，请把你签到配置文件中cookie值用xx代替后发一下文件截图。

**Comment by LGinC** [comment]
> 检查配置文件里面中文是否有 // 注释，请不要删除中文行前的 //

![image](https://user-images.githubusercontent.com/15363011/133381836-c21e1a2b-7957-4b06-8445-d796a3bc02a8.png)

**Comment by night-raise** [comment]
@LGinC 这个是猫昨天弄错了，不是配置文件的问题，是返回数据的编码问题。

**Comment by night-raise** [comment]
@LGinC 出错原因很可能是你的 cookie 过期了或者错误了，可以如下尝试：

将张大妈脚本中的20行改为以下内容：

~~~python
res=session.get(url="https://zhiyou.smzdm.com/user/info/jsonp_get_current")
print(res)
current =  res.json()
~~~

然后执行一次脚本查看输出。

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/133399627-1ac7beb0-525c-4afc-983d-d38086dd16a7.png)
![image](https://user-images.githubusercontent.com/15363011/133399704-7423cfeb-0e28-4767-b1dd-f6b2e9c0334e.png)
看来是`session.get()`这里报错的

**Comment by night-raise** [comment]
@LGinC 这样，先吧try except注释掉，看详细的报错堆栈信息

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/133405127-a1869ffe-2915-4c33-ba35-790f41efa170.png)

**Comment by night-raise** [comment]
经过多次讨论和测试，此问题一直没有复现，初步怀疑是cookie错误或者过期，请重新抓取。

**Comment by Oreomeow** [comment]
> Traceback (most recent call last):
>   File "Oreomeow_checkinpanel_master_ck_smzdm.py", line 74, in <module>
>     res = SmzdmCheckIn(smzdm_cookie_list=_smzdm_cookie_list).main()
>   File "Oreomeow_checkinpanel_master_ck_smzdm.py", line 65, in main
>     sign_msg = self.sign(session=session)
>   File "Oreomeow_checkinpanel_master_ck_smzdm.py", line 20, in sign
>     res=session.get(url="https://zhiyou.smzdm.com/user/info/jsonp_get_current")

如果加了群的可以群内交流一下，可能需要你的 ck 测试一下

**Comment by LGinC** [comment]
> 如果加了群的可以群内交流一下，可能需要你的 ck 测试一下
没找到加群链接

**Comment by night-raise** [comment]
@LGinC https://t.me/joinchat/lZWAfg5IXc5mY2I9

**Comment by LGinC** [comment]
以解决 cookies里包含中文导致编码失败
`"props":{"$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":"","$latest_landing_page":"https://post.smzdm.com/p/aqno9lwx/"}`

把props这段儿从cookies里删除就可以了
