### ISSUE TITLE
为什么我的提示路径是/ql/data/config/check.toml

### ISSUE THREAD

**Issue by wgwi007** [Oreomeow/checkinpanel#140]
路径不是/ql/config/check.toml吗？哪一步错了呢？/ql/data/config/check.toml这里面不能更改里面的数据，也上传不了

**Comment by Oreomeow** [comment]
新版青龙提示 `/ql/data/config/check.toml`，请确认你的版本

**Comment by wgwi007** [comment]
我在网页显示的是2.11.3，但是日志显示是2.12+，要什么版本才行呢？

**Comment by Oreomeow** [comment]
@wgwi007 你是不是升级过又降版本了

**Comment by wgwi007** [comment]
我忘了，不过清楚原因就好办了，我重新弄低版本青龙，感谢大佬回复

**Comment by wgwi007** [comment]
真是晕倒了，把青龙面板全删了，新拉的2.10.13，但运行日志还是显示2.12+。

尝试检查运行环境...
成功，当前环境为: 青龙面板(v2.12.0+)。
环境检查结束。

配置文件 (notify.toml) 检查开始...
未找到配置文件（不一定是错误），路径为: /ql/data/config/notify.toml。
配置文件检查结束。

checkinpanel 当前版本：20220718-4-120，最新版本：20220718-4-120

配置文件 (check.toml) 检查开始...
在 /ql/data/config/check.toml 发现配置文件。
配置文件检查结束。

海底捞会员签到 推送内容为空

**Comment by Oreomeow** [comment]
@wgwi007 把 /ql/data 文件夹清理干净

**Comment by wgwi007** [comment]
基本上弄好了，正常使用，COOKIE也填了，就是好多提示配置文件格式错误，极少数能用！都是填的COOKIE值啊，就是跟模板中的项不太一样，头大啊
