### ISSUE TITLE
错误：配置文件 /ql/config/check.json5 格式不对，请在 https://verytoolz.com/json5-validator.html 中检查格式

### ISSUE THREAD

**Issue by cc892786825** [Oreomeow/checkinpanel#16]
错误：配置文件 /ql/config/check.json5 格式不对，请在 https://verytoolz.com/json5-validator.html 中检查格式   是什么原因？

**Comment by night-raise** [comment]
@cc892786825 把你 /ql/config/check.json5  粘贴到那个网址中检查格式，就是配置文件你改的格式错了。

json5 的语法在项目 readme 中有链接。
