### ISSUE TITLE
什么值得买签到失败

### ISSUE THREAD

**Issue by zhouyang2021** [Oreomeow/checkinpanel#17]
错误信息: 'latin-1' codec can't encode characters in position 947-950: ordinal not in range(256)

**Comment by night-raise** [comment]
@zhouyang2021 截图你的 checkin.json ，可以给关键地方打码。
看smzdm的cookie有没有中文。

**Comment by Oreomeow** [comment]
#14 参考一下

**Comment by zhouyang2021** [comment]
谢谢，看参考以弄懂
