### ISSUE TITLE
哔咔漫画签到报错

### ISSUE THREAD

**Issue by PianCat** [Oreomeow/checkinpanel#186]
报错为：
签到状态: HTTPSConnectionPool(host='picaapi.picacomic.com', port=443): Max retries exceeded with url: /auth/sign-in (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f263b82bdc0>: Failed to establish a new connection: [Errno 101] Network unreachable'))

另一个基于GA版本的三天前更改了一些东西：
https://github.com/PianCat/MayoBlueSky-Actions/blob/master/function/bika/bika.py

**Comment by PianCat** [comment]
能否让哔咔走代理（？

**Comment by Amongsterdevil** [comment]
我不需要签名。在。我已经有很多问题
