### ISSUE TITLE
老哥，我引用下你的配信文件哈，

### ISSUE THREAD

**Issue by Mashiro2000** [Oreomeow/checkinpanel#32]
我的个人项目配信文件不齐全，想要直接引用贵项目的配信文件，望同意 😀

**Comment by Oreomeow** [comment]
> 我的个人项目配信文件不齐全，想要直接引用贵项目的配信文件，望同意 😀

随意哈哈哈，你可以用那个 `notify_ntr_older.py`，那个通知文件没有引入我这个项目的 `json5` 和`环境检测模块`。新增这个就是为云函数等环境服务的，本就有推广到多项目的意图。

**Comment by Oreomeow** [comment]
``` python
# 首先读取 面板变量 或者 github action 运行变量
for k in push_config:
    if os.getenv(k):
        v = os.getenv(k)
        push_config[k] = v
```

这个记得加上，还有 `import json5 as json` 直接改成 `import json` 就可以了

**Comment by Mashiro2000** [comment]
好的

**Comment by shufflewzc** [comment]
@Mashiro2000 好

**Comment by FangDoudouY** [comment]
@Mashiro2000 嗯嗯  知道了

**Comment by Oreomeow** [comment]
> 好的

发现 `json5` 多了个 `quote_keys` 的变量会导致二者不兼容，我测试下把它还原成 `json` 原版的

**Comment by Oreomeow** [comment]
已删除 `quote_keys` ，可以选择使用 [notify_mtr_json](https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_json.py)

**Comment by Mashiro2000** [comment]
> 已删除 `quote_keys` ，可以选择使用 [notify_mtr_json](https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_json.py)

我使用
```python
# 第三方库
try:
    import json5 as json
except ModuleNotFoundError:
    print("缺少json5依赖！程序将尝试安装依赖！")
    os.system("pip3 install json5 -i https://pypi.tuna.tsinghua.edu.cn/simple")
    os.execl(sys.executable, 'python3', __file__, *sys.argv)
```
下载依赖

**Comment by Oreomeow** [comment]
@Mashiro2000 也可以 hhh，不使用第三方库 json5 的话可以用那个文件

**Comment by Mashiro2000** [comment]
> @Mashiro2000 也可以 hhh，不使用第三方库 json5 的话可以用那个文件

嗯嗯
