### ISSUE TITLE
青龙面板通知优先级建议。

### ISSUE THREAD

**Issue by wingser** [Oreomeow/checkinpanel#38]
签到面板会默认识别青龙，并加载青龙config.sh里面的通知变量。

我同时也配置了notify.json5里面的通知变量，是使用了不同的通知。

不过发现配置的Notify.json5里面的变量没有生效。脚本还是默认加载了青龙的通知变量。请问这个可否默认本系统的json5通知变量优先级最高，如果找不到，再去加载config.sh的通知变量，或者可以配置指定加载的路径。

ps：我使用的是企业微信应用通知。

**Comment by Oreomeow** [comment]
本来就是 notify.json5 最高，很久没有更新这个文件了，待我检查一下

**Comment by Oreomeow** [comment]
打印日志截图发一下

**Comment by runishiwo** [comment]
这个我是正常的，就是用的notify.json5得通知，没有青龙的

**Comment by wingser** [comment]
我py正常，但是JS取到了青龙的配置，我再检查一下。

**Comment by Oreomeow** [comment]
> 我py正常，但是JS取到了青龙的配置，我再检查一下。

你说 JS 啊，没写 hhh，之后补上

**Comment by wingser** [comment]
顺便提一句【有道】的签到脚本有问题，py3报错，我改了错误，发现报cookie的错误了，我是浏览器抓的cookie，这个是一定要APP抓一遍吗？因为我看有的参数，好像是浏览器里面没有。

**Comment by Oreomeow** [comment]
@wingser 网页抓取，未发现问题

**Comment by wingser** [comment]
【1】我手机验证码登录，我最开始运行，提示脚本错误，报错如下。
Traceback (most recent call last):
  File "Oreomeow_checkinpanel_master_ck_youdao.py", line 83, in <module>
    res = YouDao(check_items=_check_items).main()
  File "Oreomeow_checkinpanel_master_ck_youdao.py", line 75, in main
    msg = self.sign(cookie)
  File "Oreomeow_checkinpanel_master_ck_youdao.py", line 68, in sign
    msg += "错误" + re.json()
TypeError: can only concatenate str (not "dict") to str



【2】然后我修改了str转换这里，语法没问题了。报错信息变成如下部分。

配置文件 (check.json5) 检查开始...
在 /ql/config/check.json5 发现配置文件。
配置文件检查结束。

有道云笔记

签到前空间: 3145M
错误{'canTryAgain': False, 'scope': 'SECURITY', 'error': '207', 'message': 'Message[AUTHENTICATION_FAILURE]: User token must be authenticated.', 'objectUser': None}



就算是自私⋯⋯我也希望那些人能够永远都有笑容⋯⋯    ----夏目友人帐
企业微信 APP 服务启动
企业微信推送成功！

## 执行结束... 2021-11-09 12:52:29 耗时 14 秒

**Comment by wingser** [comment]
我估计是不是和我每次用验证码登录有关系，我没有设置过密码。

**Comment by Oreomeow** [comment]
@wingser 已实现 JS 通知单独设置，另一个应该是没有密码缺少参数的原因。

**Comment by wingser** [comment]
感谢大佬，我去更新
