### ISSUE TITLE
:memo: 青龙依赖安装截图

### ISSUE THREAD

**Issue by Oreomeow** [Oreomeow/checkinpanel#43]
# qinglong 2.10.2

![签到依赖2 10 2](https://user-images.githubusercontent.com/62660101/141651036-1686cc5e-2b23-461d-b7ba-081fdbcbbee3.png)

# qinglong 2.10.7
![签到依赖2 10 7](https://user-images.githubusercontent.com/62660101/141651048-39426d9c-312d-4284-b4e1-067bdf5df592.png)

**Comment by Oreomeow** [comment]
# 日常状态
![image](https://user-images.githubusercontent.com/62660101/141651410-c0b59de3-3d14-4341-a506-05ed0ef9b690.png)

**Comment by naiveclub** [comment]
你好，请问你是通过什么方式安装的青龙依赖？现在最新版青龙用命令安装依赖都报错啊

**Comment by 363843342** [comment]
青龙面板的定时任务里面的 ”签到依赖“ 任务消失了，手动执行package.json或者checkins_pkg.js都报错，现在不知道怎么解决

**Comment by lbwnb1433223** [comment]
root@qinglong:/ql $ apk add libffi-dev
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

**Comment by avinrock** [comment]
> root@qinglong:/ql $ apk add libffi-dev ERROR: unable to select packages: bizCode (no such package): required by: world[bizCode] bizMsg (no such package): required by: world[bizMsg] lxml (no such package): required by: world[lxml]

我也是这个问题，老哥解决了么

**Comment by cnbb002** [comment]
遇到同样的问题，任务中并没有“签到依赖”这个任务

**Comment by Oreomeow** [comment]
> 遇到同样的问题，任务中并没有“签到依赖”这个任务

请仔细查看，按流程顺序操作

https://github.com/Oreomeow/checkinpanel#2-%E6%8B%89%E5%8F%96%E4%BB%93%E5%BA%93

**Comment by zhangxin4711** [comment]
! Finding Module::Build::Tiny on cpanmetadb failed.

最后一行有个这个，青龙2.14.7
