### ISSUE TITLE
freenom login status failed

### ISSUE THREAD

**Issue by SkysCrystal** [Oreomeow/checkinpanel#58]
基于青龙面板运行签到脚本，已运行 `签到依赖任务`，在配置文件 `check.toml` 内已填写 `email` `password` 等信息

# 对于 `ck_freenom.py` 文件

## 代码运行日志
![image](https://user-images.githubusercontent.com/49473463/144841140-cd77814e-f25f-4bba-bcdc-42f7f68603d0.png)

## 相关代码
![image](https://user-images.githubusercontent.com/49473463/144841324-5d1a8867-00d3-4d04-ad80-f211a73d962d.png)
![image](https://user-images.githubusercontent.com/49473463/144841260-e47a1f2d-4e6f-47c7-b510-362e6fa476a3.png)

我代码功底有限，不知道是不是和正则表达相关还是其他问题，烦请指教，谢谢！

**Comment by Oreomeow** [comment]
@SkysCrystal 你好，可能为网络问题，请更新后再尝试运行一次，如果还有问题再进行日志调试
