### ISSUE TITLE
我在arm64设备上运行epic脚本，它自动下载的chromium是x86的，运行就报错

### ISSUE THREAD

**Issue by wonderhong** [Oreomeow/checkinpanel#60]
![image](https://user-images.githubusercontent.com/92223669/145508718-03c7329f-63e8-4db2-b618-e63bb5fba0c8.png)
![image](https://user-images.githubusercontent.com/92223669/145509006-c793cc6f-b66e-4186-a7bb-ebb3f7ac64a4.png)

**Comment by Oreomeow** [comment]
@wonderhong 运行 ins_selenium.sh

**Comment by wonderhong** [comment]
> @wonderhong 运行 ins_selenium.sh

运行过了，还是这样

**Comment by Oreomeow** [comment]
@wonderhong 没安装成功，贴日志

**Comment by wonderhong** [comment]
> @wonderhong 没安装成功，贴日志

![image](https://user-images.githubusercontent.com/92223669/145557380-8f2cea82-628f-4d85-af92-08ad715b89cb.png)

**Comment by Oreomeow** [comment]
把 pyppeteer 卸载了重装再跑脚本

**Comment by Oreomeow** [comment]
@wonderhong 再不行加群交流，入口在标题下面的 tg 图标那里
