### ISSUE TITLE
acfun 签到报错 青龙2.10.2

### ISSUE THREAD

**Issue by FlechazoPh** [Oreomeow/checkinpanel#61]
依赖应该都装了
![image](https://user-images.githubusercontent.com/94276146/145611232-6f9156d5-08f1-4e52-9dc9-a26a4d595959.png)

**Comment by Oreomeow** [comment]
@FlechazoPh cookies 没填对

**Comment by Oreomeow** [comment]
没问题，重新运行看看

**Comment by FlechazoPh** [comment]
找到原因了，toml 配置文件里，没有把默认的那条配置删除，就会报这个错，删掉就正常了

**Comment by FlechazoPh** [comment]
另有个问题是分享任务会失败  

<img width="587" alt="image" src="https://user-images.githubusercontent.com/94276146/145667283-6ff5a3c6-af0a-437d-97c8-f2290c8a2ff5.png">

**Comment by Oreomeow** [comment]
暂时没有找到 API，之后再看

**Comment by xuchjian** [comment]
> 找到原因了，toml 配置文件里，没有把默认的那条配置删除，就会报这个错，删掉就正常了

我也是这个错，但是没读懂你这句话意思，请问怎么改

**Comment by FlechazoPh** [comment]
> > 找到原因了，toml 配置文件里，没有把默认的那条配置删除，就会报这个错，删掉就正常了
> 
> 我也是这个错，但是没读懂你这句话意思，请问怎么改

把默认的没用到的配置删掉就好了
