### ISSUE TITLE
[建议]多看阅读有几个抓取的参数名称改一下

### ISSUE THREAD

**Issue by 17huiwei** [Oreomeow/checkinpanel#66]
short_version应该是first_version
user_gender应该是男1，女2
user_id抓不到，需要到软件界面的【我的】里面看小米ID
以上已经实测通过。

**Comment by Oreomeow** [comment]
https://github.com/Oreomeow/checkinpanel/blob/be7b4414c13f7a144cfa14370a544d226f3c0920/check.sample.toml#L2

为什么不看注释呢？
