### ISSUE TITLE
天气预报多城市该如何填写？

### ISSUE THREAD

**Issue by yxnwh** [Oreomeow/checkinpanel#68]
CITY = ["深圳","上海"]这样写，提示错误
另外发现好像不用写区，直接写城市即可

**Comment by Oreomeow** [comment]
提示什么错误呢？

**Comment by yxnwh** [comment]
> 提示什么错误呢？
![image](https://user-images.githubusercontent.com/36069159/147452777-1f8fe145-8488-4f73-96e1-c8383f84b0b5.png)

**Comment by night-raise** [comment]
还麻烦加 tg 群后私发下你的toml文件，应该是你文件哪里写错了。
这么配置城市本身是没问题的。

当然你可以自己二分这个文件找找问题。
