### ISSUE TITLE
葫芦侠签到脚本运行失败

### ISSUE THREAD

**Issue by xiaoxiaofeiweb** [Oreomeow/checkinpanel#69]
葫芦侠签到脚本运行失败，不知道为啥？
![捕获](https://user-images.githubusercontent.com/95344200/147354138-d5186798-0a40-4587-b77c-89d850bb1f91.PNG)

**Comment by night-raise** [comment]
看起来是 cookie 过期之类的东西？先试试更新 cookie？

**Comment by xiaoxiaofeiweb** [comment]
> 看起来是 cookie 过期之类的东西？先试试更新 cookie？

这个是直接登录账号

**Comment by Oreomeow** [comment]
已修复
