### ISSUE TITLE
青龙安装依赖的命令是什么？ 拉取的库也没有安装签到依赖的任务啊，没看明白。。

### ISSUE THREAD

**Issue by jjjyyyllll** [Oreomeow/checkinpanel#70]
青龙安装依赖的命令是什么？ 拉取的库也没有安装签到依赖的任务啊，没看明白。。

**Comment by 363843342** [comment]
同问+1

**Comment by 363843342** [comment]
已经解决https://github.com/Oreomeow/checkinpanel/issues/74#issuecomment-1003835951
