### ISSUE TITLE
签到依赖反馈

### ISSUE THREAD

**Issue by TT-IPIP** [Oreomeow/checkinpanel#72]
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.9-29-gbb76c58772 [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main]
v3.12.9-29-gbb76c58772 [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community]
OK: 12754 distinct packages available
bash 已安装
curl 已安装
ERROR: unable to select packages:
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
.......... retry in 5 seconds ..........
.......... apk add gcc begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add gcc !!
git 已安装
jq 已安装
ERROR: unable to select packages:
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add libffi-dev !!
ERROR: unable to select packages:
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
.......... retry in 5 seconds ..........
.......... apk add make begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add make !!
ERROR: unable to select packages:
.......... apk add musl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add musl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add musl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add musl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add musl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add musl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add musl-dev !!
ERROR: unable to select packages:
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add openssl-dev !!
perl 已安装
ERROR: unable to select packages:
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add perl-app-cpanminus !!
ERROR: unable to select packages:
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add perl-dev !!
py3-pip 已安装
python3 已安装
ERROR: unable to select packages:
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add python3-dev !!
wget 已安装
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install bs4 begin ..........
---------- pip3 install bs4 succeed ----------
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nuzzlw59/cffi_97bfc47236f24e7cadbea1213ab3c668/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nuzzlw59/cffi_97bfc47236f24e7cadbea1213ab3c668/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1s_b2ejz/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/cffi
         cwd: /tmp/pip-install-nuzzlw59/cffi_97bfc47236f24e7cadbea1213ab3c668/
    Complete output (48 lines):
    unable to execute 'gcc': No such file or directory
    unable to execute 'gcc': No such file or directory
    
        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.libera.chat.)
    
        Trying to continue anyway.  If you are trying to install CFFI from
        a build done in a different context, you can ignore this warning.
    
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/c
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nuzzlw59/cffi_97bfc47236f24e7cadbea1213ab3c668/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nuzzlw59/cffi_97bfc47236f24e7cadbea1213ab3c668/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1s_b2ejz/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/cffi Check the logs for full command output.
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
!! 自动安装失败，请尝试进入容器后执行 pip3 install cryptography !!
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install pyaes begin ..........
---------- pip3 install pyaes succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install pyppeteer begin ..........
---------- pip3 install pyppeteer succeed ----------
requests 已安装
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install rsa begin ..........
---------- pip3 install rsa succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install schedule begin ..........
---------- pip3 install schedule succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install tomli begin ..........
---------- pip3 install tomli succeed ----------

added 34 packages, and audited 35 packages in 4s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
@iarna/toml 已正确安装
axios 已正确安装
crypto-js 已正确安装
got 已正确安装
checkinpanel@1.0.0 /ql/scripts/Oreomeow_checkinpanel_master
├── @iarna/toml@2.2.5
├── axios@0.23.0
├── crypto-js@4.1.1
└── got@11.8.3

ins_pkg.sh: line 122: cpanm: command not found
.......... cpanm -fn App::cpm begin ..........
---------- cpanm -fn App::cpm succeed ----------
cpm 0.997007 (./cpm)
This is a self-contained version, 0.997007 (https://github.com/skaji/cpm/tree/0.997007)
perl version v5.30.3 (perl)

  %Config:
    archname=x86_64-linux-thread-multi
    installsitelib=/usr/local/share/perl5/site_perl
    installsitebin=/usr/local/bin
    installman1dir=/usr/share/man/man1
    installman3dir=/usr/share/man/man3
    sitearchexp=/usr/local/lib/perl5/site_perl
    sitelibexp=/usr/local/share/perl5/site_perl
    vendorarch=/usr/lib/perl5/vendor_perl
    vendorlibexp=/usr/share/perl5/vendor_perl
    archlibexp=/usr/lib/perl5/core_perl
    privlibexp=/usr/share/perl5/core_perl
  %ENV:
  @INC:
    FatPacked::94399232135472=HASH(0x55db08b2d130)
    /usr/local/lib/perl5/site_perl
    /usr/local/share/perl5/site_perl
    /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/core_perl
    /usr/share/perl5/core_perl
No documentation found for "File::Slurp".
ins_pkg.sh: line 138: cpm: command not found
.......... cpm install -g File::Slurp begin ..........
---------- cpm install -g File::Slurp succeed ----------
No documentation found for "JSON5".
ins_pkg.sh: line 138: cpm: command not found
.......... cpm install -g JSON5 begin ..........
---------- cpm install -g JSON5 succeed ----------
No documentation found for "TOML::Dumper".
ins_pkg.sh: line 138: cpm: command not found
.......... cpm install -g TOML::Dumper begin ..........
---------- cpm install -g TOML::Dumper succeed ----------

**Comment by TT-IPIP** [comment]
自动安装失败，请尝试进入容器后执行也失败
$ apk add make
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

**Comment by night-raise** [comment]
root@qinglong:/ql $ apk add make
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
OK: 811 MiB in 253 packages

这边没问题。建议试试起个新青龙对比测试下。

**Comment by TT-IPIP** [comment]
机器的问题，重装系统就可以了
