### ISSUE TITLE
作者你好！请教一下EPIC运行问题

### ISSUE THREAD

**Issue by LQ2002** [Oreomeow/checkinpanel#73]
![image](https://user-images.githubusercontent.com/50812010/147646644-0926fdf9-5a15-4798-8ef2-849ce9a98ffd.png)
在运行epic的脚本出现以上这种问题怎么解决吖？

**Comment by night-raise** [comment]
参见 https://github.com/Oreomeow/checkinpanel/issues/71，请在那个问题下面回复。
