### ISSUE TITLE
青龙面板拉取的库后，定时任务里面的”签到依赖“消失

### ISSUE THREAD

**Issue by 363843342** [Oreomeow/checkinpanel#74]
![image](https://user-images.githubusercontent.com/71557954/147846070-64f78a2f-bcf8-41ce-b76f-259b100b12ad.png)
如图所示，60项任务里面没有”签到依赖“这个选项，且无法利用命令手动执行

**Comment by night-raise** [comment]
拉库命令应该不对，请粘贴你的拉库命令并检查是否包含了 `ins_pkg.sh`

**Comment by 363843342** [comment]
感谢已经解决，
原因是ql目录下config目录下的config.sh里面的RepoFileExtensions="js pl py sh ts"修改后没有保存。估计该错误都是这个原因。
<img width="301" alt="屏幕截图 2022-01-03 101302" src="https://user-images.githubusercontent.com/71557954/147895766-f004059c-e45f-42ba-9cd0-1674543674f6.png">
<img width="458" alt="屏幕截图 2022-01-03 101320" src="https://user-images.githubusercontent.com/71557954/147895777-a0207cde-aba9-41a4-98af-6ff350180989.png">


> 拉库命令应该不对，请粘贴你的拉库命令并检查是否包含了`ins_pkg.sh`
