### ISSUE TITLE
青龙面板v2.10.13拉库后没有签到依赖定时任务

### ISSUE THREAD

**Issue by liuzj288** [Oreomeow/checkinpanel#76]
1.拉库命令如图

2.更新后没有签到依赖任务

![Snipaste_2022-01-02_04-14-31](https://user-images.githubusercontent.com/13833404/147859373-2e077188-128b-45c6-a505-93a4e53ba252.png)

3.命令行执行也一样
![Snipaste_2022-01-02_04-16-33](https://user-images.githubusercontent.com/13833404/147859386-096596ea-56f0-434e-9ef7-a413d077c748.png)

**Comment by 363843342** [comment]
已经解决https://github.com/Oreomeow/checkinpanel/issues/74#issuecomment-1003835951



> 1.拉库命令如图
> 
> 2.更新后没有签到依赖任务
> 
> ![Snipaste_2022-01-02_04-14-31](https://user-images.githubusercontent.com/13833404/147859373-2e077188-128b-45c6-a505-93a4e53ba252.png)
> 

> 3.命令行执行也一样 ![Snipaste_2022-01-02_04-16-33](https://user-images.githubusercontent.com/13833404/147859386-096596ea-56f0-434e-9ef7-a413d077c748.png)

**Comment by night-raise** [comment]
感谢二楼的帮助回复，你可以按照他的方法试试。

如果不对的话提供下这个文件相关行的截图。
