### ISSUE TITLE
AcFun无法签到

### ISSUE THREAD

**Issue by LQ2002** [Oreomeow/checkinpanel#77]
![image](https://user-images.githubusercontent.com/50812010/148056969-b4e5b163-d6d0-4da0-a10e-5774ddce44fb.png)
依赖都运行安装了

**Comment by night-raise** [comment]
一般是配置文件错误或者 cookie 过期。试着换一个cookie试试。

**Comment by 2eronia** [comment]
> 一般是配置文件错误或者 cookie 过期。试着换一个cookie试试。

可是toml里的Acfun签到示例，是填手机和密码的…
