### ISSUE TITLE
请教，请问这是怎么回事

### ISSUE THREAD

**Issue by GD2021** [Oreomeow/checkinpanel#78]
![image](https://user-images.githubusercontent.com/81171294/148084888-709a25f4-f97d-4e95-b0ae-55502e6f440e.png)

**Comment by night-raise** [comment]
@GD2021 配置文件格式不正确吧，建议检查下格式。

**Comment by GD2021** [comment]
配置文件没问题呀，一直都是这样配置的
![image](https://user-images.githubusercontent.com/81171294/148248434-7b5f4e86-6217-43cb-97dc-2e0d760fa61d.png)
![image](https://user-images.githubusercontent.com/81171294/148248500-92329070-2fc0-4d24-9da1-5d87ccb963b3.png)
![image](https://user-images.githubusercontent.com/81171294/148248559-c1fe8768-58a3-4abe-b6f1-bd84ccda8299.png)

**Comment by Oreomeow** [comment]
ture 拼写错误

**Comment by d-w-x** [comment]
> ture 拼写错误

猫啊，走吧，别丢人了...

**Comment by xuchjian** [comment]
密码填手机号，手机号填了密码？

**Comment by FangDoudouY** [comment]
> 真的拼写错误

猫猫求集成进去
https://github.com/Womsxd/AutoMihoyoBBS

**Comment by night-raise** [comment]
@FangDoudouY 请新开 issue

**Comment by FangDoudouY** [comment]
@night-raise 你特么不看看我名字的么  我有不懂  这是我在用的
