### ISSUE TITLE
[新增签到] 希望增加免费机场的签到

### ISSUE THREAD

**Issue by FlechazoPh** [Oreomeow/checkinpanel#79]
签到可以免费获得几 GB 的流量和免费天数
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/94276146/148153420-8cfdfe9a-6d76-4da9-a337-40439744336a.png">

登录用的用户名不是邮箱

**Comment by FlechazoPh** [comment]
经测试发现，用邮箱当用户名去注册，可以直接使用这个脚本签到，但是用普通的用户名注册的账户就不行，能在脚本里 使用 email 配置字段的时候兼容下么,让不是邮箱的用户名也可以正常登录签到,例如在使用 email 字段的时候不用 "@" 字符去分割登录用户名

**Comment by FlechazoPh** [comment]
改了下，这部分逻辑，测试可以正常使用
`````````````````    
@staticmethod
    def checkin(url, email, password):
        url = url.rstrip("/")
        email = email.split("@")
        if 	len(email) > 1 :
            email = email[0] + "%40" + email[1]
        else:
            email = email[0]

        
        session = requests.session()
        """
        以下 except 都是用来捕获当 requests 请求出现异常时，
        通过捕获然后等待网络情况的变化，以此来保护程序的不间断运行
        """

````````````

**Comment by night-raise** [comment]
@FlechazoPh 感觉回复，这里具体逻辑需要等猫猫出现看看怎么加。

**Comment by 363843342** [comment]
这边遇到其它问题，签到日志404，怎么修改才能拥有代理配置，全局代理其它签到容易出问题
<img width="388" alt="image" src="https://user-images.githubusercontent.com/71557954/148666123-028c4b9c-1015-4dc9-be05-28b2464d68ce.png">
