### ISSUE TITLE
企业微信推送失败

### ISSUE THREAD

**Issue by liberize** [Oreomeow/checkinpanel#83]
青龙环境，配了QYWX_AM，青龙的其它通知正常

错误信息如下：
企业微信推送失败！错误信息：invalid media_id, hint: [1641614610277970749078459], from ip: 58.248.193.31, more info at https://open.work.weixin.qq.com/devtool/query?e=40007

**Comment by night-raise** [comment]
从错误来看，就是你 QYWX_AM 整个参数错误了，你需要自己检查对应的参数。

**Comment by liberize** [comment]
卸载了

**Comment by night-raise** [comment]
@liberize 卸载?卸载啥？
