### ISSUE TITLE
所有脚本运行提示check.toml 格式不对

### ISSUE THREAD

**Issue by maxage** [Oreomeow/checkinpanel#85]
除了填写让填写的东西，其它都没动。。。
错误：配置文件 /ql/config/check.toml 格式不对，请学习 https://toml.io/cn/v1.0.0
错误信息：
Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/utils.py", line 37, in get_data
    DATA = tomli.load(open(check_config, "rb"))
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 64, in load
    return loads(s, parse_float=parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 123, in loads
    raise suffixed_err(
tomli.TOMLDecodeError: Expected newline or end of document after a statement (at line 88, column 280)

**Comment by GD2021** [comment]
尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
未找到配置文件（不一定是错误），路径为: /ql/config/notify.toml。
配置文件检查结束。

checkinpanel 当前版本：20211219-4-020，不在 8-12 点内，跳过版本检查。

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

错误：配置文件 /ql/config/check.toml 格式不对，请学习 https://toml.io/cn/v1.0.0
错误信息：
Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/utils.py", line 37, in get_data
    DATA = tomli.load(open(check_config, "rb"))
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 64, in load
    return loads(s, parse_float=parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 99, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 327, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 362, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 642, in parse_value
    raise suffixed_err(src, pos, "Invalid value")
tomli.TOMLDecodeError: Invalid value (at line 8, column 14)


## 执行结束... 2022-01-10 13:12:02 耗时 1 秒

**Comment by maxage** [comment]
一样提示！不知道怎么解决！

**Comment by linuxi** [comment]
下载check.sample.toml重新填CK试试

**Comment by night-raise** [comment]
这个我也没什么好办法，它说格式不对那的确不对...自己检查吧。

**Comment by GD2021** [comment]
## 开始执行... 2022-01-16 00:28:55

fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
v3.12.9-29-gbb76c58772 [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main]
v3.12.9-30-g69c35febbc [http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community]
OK: 12624 distinct packages available
bash 已安装
curl 已安装
gcc 已安装
git 已安装
jq 已安装
ERROR: unable to select packages:
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add libffi-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add libffi-dev !!
make 已安装
musl-dev 已安装
ERROR: unable to select packages:
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add openssl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add openssl-dev !!
perl 已安装
ERROR: unable to select packages:
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-app-cpanminus begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add perl-app-cpanminus !!
ERROR: unable to select packages:
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add perl-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add perl-dev !!
py3-pip 已安装
python3 已安装
ERROR: unable to select packages:
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
.......... retry in 5 seconds ..........
.......... apk add python3-dev begin ..........
!! 自动安装失败，请尝试进入容器后执行 apk add python3-dev !!
wget 已安装
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install bs4 begin ..........
---------- pip3 install bs4 succeed ----------
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2lwyke1h/cffi_9a050992314f43159327df2818032c6d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2lwyke1h/cffi_9a050992314f43159327df2818032c6d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zyvi3ord/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/cffi
         cwd: /tmp/pip-install-2lwyke1h/cffi_9a050992314f43159327df2818032c6d/
    Complete output (36 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.8
    creating build/lib.linux-aarch64-3.8/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/cparser.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/error.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/__init__.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/model.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/recompiler.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/api.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/lock.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/commontypes.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/verifier.py -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/_embedding.h -> build/lib.linux-aarch64-3.8/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.8/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-aarch64-3.8
    creating build/temp.linux-aarch64-3.8/c
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.8/c/_cffi_backend.o
    c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
        2 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2lwyke1h/cffi_9a050992314f43159327df2818032c6d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2lwyke1h/cffi_9a050992314f43159327df2818032c6d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zyvi3ord/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/cffi Check the logs for full command output.
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
.......... retry in 5 seconds ..........
.......... pip3 install cryptography begin ..........
!! 自动安装失败，请尝试进入容器后执行 pip3 install cryptography !!
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install pyaes begin ..........
---------- pip3 install pyaes succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install pyppeteer begin ..........
---------- pip3 install pyppeteer succeed ----------
requests 已安装
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install rsa begin ..........
---------- pip3 install rsa succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install schedule begin ..........
---------- pip3 install schedule succeed ----------
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.......... pip3 install tomli begin ..........
---------- pip3 install tomli succeed ----------

added 34 packages, and audited 35 packages in 10s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
@iarna/toml 已正确安装
axios 已正确安装
crypto-js 已正确安装
got 已正确安装
checkinpanel@1.0.0 /ql/scripts/Oreomeow_checkinpanel_master
├── @iarna/toml@2.2.5
├── axios@0.23.0
├── crypto-js@4.1.1
└── got@11.8.3

ins_pkg.sh: line 122: cpanm: command not found
.......... cpanm -fn App::cpm begin ..........
---------- cpanm -fn App::cpm succeed ----------
cpm 0.997007 (./cpm)
This is a self-contained version, 0.997007 (https://github.com/skaji/cpm/tree/0.997007)
perl version v5.30.3 (perl)

  %Config:
    archname=aarch64-linux-thread-multi
    installsitelib=/usr/local/share/perl5/site_perl
    installsitebin=/usr/local/bin
    installman1dir=/usr/share/man/man1
    installman3dir=/usr/share/man/man3
    sitearchexp=/usr/local/lib/perl5/site_perl
    sitelibexp=/usr/local/share/perl5/site_perl
    vendorarch=/usr/lib/perl5/vendor_perl
    vendorlibexp=/usr/share/perl5/vendor_perl
    archlibexp=/usr/lib/perl5/core_perl
    privlibexp=/usr/share/perl5/core_perl
  %ENV:
  @INC:
    FatPacked::367328212032=HASH(0x558677b440)
    /usr/local/lib/perl5/site_perl
    /usr/local/share/perl5/site_perl
    /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/core_perl
    /usr/share/perl5/core_perl
No documentation found for "File::Slurp".
ins_pkg.sh: line 138: cpm: command not found
.......... cpm install -g File::Slurp begin ..........
---------- cpm install -g File::Slurp succeed ----------
No documentation found for "JSON5".
ins_pkg.sh: line 138: cpm: command not found
.......... cpm install -g JSON5 begin ..........
---------- cpm install -g JSON5 succeed ----------
No documentation found for "TOML::Dumper".
ins_pkg.sh: line 138: cpm: command not found
.......... cpm install -g TOML::Dumper begin ..........
---------- cpm install -g TOML::Dumper succeed ----------

## 执行结束... 2022-01-16 00:33:10 耗时 255 秒

依赖有的不成功怎么办？

**Comment by night-raise** [comment]
刚刚全新安装的青龙没有问题，考虑检查网络链接或者重装。

![image](https://user-images.githubusercontent.com/90231086/149896008-33f98459-f446-47e6-8726-8dd1ce1969f5.png)

**Comment by Eao-Kind** [comment]
看看是不是百度贴吧的cookie有问题？，排除了一下发现百度cookie有错
