### ISSUE TITLE
在线工具的脚本可能失效了。王者营地抓包有没有什么好办法。

### ISSUE THREAD

**Issue by cike-567** [Oreomeow/checkinpanel#88]
<img width="392" alt="屏幕截图 2022-01-18 161534" src="https://user-images.githubusercontent.com/68531942/149897554-e9d490ef-0240-4a64-b22c-1b8064719c81.png">
我是通过浏览器f12获得的ck，ck换了几个，脚本日志都显示ck过期。我对比了几次获得的ck，发现_access每次刷新网页都不一样。
王者营地抓了半个小时都没抓到。用的软件是小黄鸟，有更好的办法吗

**Comment by night-raise** [comment]
@cike-567 在线工具我刚刚抓过是可以的，你抓点击签到的那个请求的ck。 王者不知道。

**Comment by monkey-sking** [comment]
抓了后，第二天会失效。。。。当天提示已经签到了

**Comment by night-raise** [comment]
在线工具 你抓的包有问题，我的成功挂了几天了。
