### ISSUE TITLE
青龙的拷贝文件应该怎么操作

### ISSUE THREAD

**Issue by zhiyoua** [Oreomeow/checkinpanel#93]
在定时任务里当拉库操作根本没有反应…求解
![Screenshot_20220131_002610](https://user-images.githubusercontent.com/98383459/151708080-2682b303-13f7-4719-b113-24d96575e43c.jpg)

**Comment by Oreomeow** [comment]
@zhiyoua 从第一步就能找到答案

**Comment by zhiyoua** [comment]
这…还是我太菜了…没懂…我在进青龙的页面后台用这个也是没反应…

**Comment by Oreomeow** [comment]
@zhiyoua 额 ssh 上输入 docker exec -it 容器名 bash

**Comment by zhiyoua** [comment]
这不还是进青龙容器内部…我确实是进了再输的那个，一点反应没有

**Comment by Oreomeow** [comment]
@zhiyoua 要啥反应，就是把 /ql/repo 里的模板文件复制到 /ql/config 里。直接仓库里下载 check.sample.toml 然后改名为 check.toml 再上传 /ql/config 文件夹也是一样的

**Comment by zhiyoua** [comment]
懂了懂了，我直接复制粘贴过去了，谢谢大佬
